### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by lengyue1024** [jaywcjlove/sb#2]
请问是否有Email、csdn的svg图标，还有就是怎么制作你这种svg图标

**Comment by jaywcjlove** [comment]
@lengyue1024 可以有 `Email`, `csdn` 的图标，图标都是 [Sketch](https://sketchapp.com/) 制作的，源文件在仓库中，你也可以用 `PS` 也可以。

源文件：https://github.com/jaywcjlove/sb/tree/gh-pages/svg

**Comment by lengyue1024** [comment]
@jaywcjlove 谢谢您，但是我现在还不会用`ps`,您有时间了可以做个`Email`的图标吗?字样为`Email`.

**Comment by jaywcjlove** [comment]
![](https://jaywcjlove.github.io/sb/ico/weibo.svg)

这个大小的？
@lengyue1024

**Comment by lengyue1024** [comment]
对，谢谢您了

**Comment by jaywcjlove** [comment]
![](https://jaywcjlove.github.io/sb/ico/csdn.svg) ![](https://jaywcjlove.github.io/sb/ico/email.svg)

@lengyue1024

**Comment by lengyue1024** [comment]
谢谢您

**Comment by jaywcjlove** [comment]
```markdown
![](https://jaywcjlove.github.io/sb/ico/csdn.svg)
![](https://jaywcjlove.github.io/sb/ico/email.svg)
```
