### ISSUE TITLE
GitHub如何显示SVG格式图

### ISSUE THREAD

**Issue by ssnhd** [jaywcjlove/sb#3]
您好，SVG图上传到GitHub库文件夹，复制图片地址发现地址特别长，使用Markdown编辑不能显示该图片，请问是何原因？

**Comment by jaywcjlove** [comment]
@masonvip 这样不能显示？

```markdown
![](http://jaywcjlove.github.io/sb/progressed/94.svg)
```

**Comment by masonvip** [comment]
格式是这样的，但是我复制的图片地址超级长，有上千个字符，不知道什么原因。

**Comment by ssnhd** [comment]
![](https://github.com/masonvip/masonvip.github.io/blob/master/file01/%E4%B8%8D%E8%83%BD%E6%98%BE%E7%A4%BASVG.png?raw=true)
* 格式是对的，但是我复制的图片地址超级长，有上千个字符，不知道什么原因。 
* 在GitHub的Markdown里无法显示。

**Comment by jaywcjlove** [comment]
GitHub资源你可以借助 工具 https://raw.githack.com/ 来预览你仓库中的资源

例如我仓库的svg 图标 

```
https://github.com/uiwjs/uiwjs.github.io/blob/dev/src/assets/logo-README.svg
```

通过 githack 转换成

```
https://raw.githack.com/uiwjs/uiwjs.github.io/dev/src/assets/logo-README.svg
```

**Comment by ssnhd** [comment]
了解，感谢！
